config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server, at: '/cable'

  resources :chat_rooms

  root 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  # Relationships
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  # Relationships
  belongs_to :user
  belongs_to :chat_room

  # Validations
  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }

  # Callbacks
  after_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Extensions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Relationships
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Callbacks
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    render locals: { chat_rooms: chat_rooms }
  end

  def new
    render locals: { chat_room: ChatRoom.new }
  end

  def create
    chat_room = current_user.chat_rooms.build(chat_room_params)
    if chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    render locals: { chat_room: chat_room, message: Message.new }
  end

  def destroy
    message.destroy
    redirect_to :back
  end

  private

  def chat_room
    return @chat_room if defined?(@chat_room)
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  end

  def chat_rooms
    return @chat_rooms if defined?(@chat_rooms)
    @chat_rooms = ChatRoom.all
  end

  def message
    return @message if defined?(@message)
    @message = current_user.messages.find_by(id: params[:message_id])
  end

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  def public_chat_rooms_list
    ChatRoom.all
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= active_link_to "Enter #{chat_room.title}", chat_room_path(chat_room), class: 'nav-link' %></li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for chat_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit 'Add!', class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1 class="card-header"><%= chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= chat_room.id %>">
  <%= render chat_room.messages %>
</div>

<hr>

<%= render partial: 'messages/form', locals: { chat_room: chat_room, message: message } %>

app/views/chat_rooms/update_message.js.erb
$('#edit-message-<%= @message.id.to_s %>').html("<%= j (render partial: 'messages/form', locals: { message: @message, chat_room: @chat_room }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLiveChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-dark bg-inverse">
      <%= link_to 'CableChat', root_path, class: 'navbar-brand' %>

      <% if user_signed_in? %>
          <ul class="nav navbar-nav pull-xs-right">
            <li class="nav-item">
              <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
            </li>
            <li class="nav-item active">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          </ul>
      <% end %>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-5 col-lg-4 col-xl-3">
          <%= render 'shared/sidebar' %>
        </div>
        <div class="col-md-7 col-lg-8 col-xl-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for message, url: '#', remote: true do |f| %>
    <%= hidden_field_tag 'chat_room_id', chat_room.id %>
    <div class="form-group">
      <%= f.text_area :body, class: 'form-control', placeholder: 'Enter your message text..' %>
      <small class="text-muted">From 2 to 1000 characters</small>
    </div>

    <%= f.submit 'Send', class: 'btn btn-primary btn-sma' %>
<% end %>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-9" id="edit-message-<%= message.id %>">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
      <div class="col-md-1">
        <%= form_for message, url: '#', html: { method: 'delete', id: 'destroy-message' }, remote: true do %>
          <%= hidden_field_tag 'message_id', message.id %>
          <%= button_tag(class: 'btn btn-sm btn-outline-danger') do %>
            <%= fa_icon 'trash-o' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <%= render public_chat_rooms_list %>
</ul>